apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: algohive-ingress
  namespace: algohive
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "30"
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: algohive-server
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: algohive-client
                port:
                  number: 80
