apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: algohive-beeapi
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    # Sync wave 0 : BeeAPI démarre en dernier, une fois core prêt
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/ShiftTechSecurity/eks-ec2-tf.git
    targetRevision: main
    path: k8s-v2/overlays/production/beeapi
  destination:
    name: in-cluster
    namespace: algohive
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
