apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: algohive-kubeview
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  project: default
  source:
    repoURL: https://code.benco.io/kubeview/deploy/helm
    chart: kubeview
    targetRevision: "2.0.6"
    helm:
      releaseName: kubeview
      values: |
        ingress:
          enabled: false
        loadBalancer:
          enabled: true
        serviceAnnotations:
          service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
  destination:
    name: in-cluster
    namespace: kubeview
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
